In [145]:
import pandas as pd
d=pd.read_csv("/train.csv")
print(d)
print(d.isnull())

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [146]:
y=d['price_range']

In [147]:
x=d.drop('price_range',axis=1)

In [148]:
print(y)
print(x)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64
      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999    

In [149]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrain_norm=scaler.fit_transform(x)

In [151]:
print(Xtrain_norm)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [152]:
from sklearn .model_selection import train_test_split

In [153]:
x_train,x_test,y_train,y_test=train_test_split(xtrain_norm,y,test_size=0.3)

In [154]:
print(x_train)

[[0.21175685 0.         0.32       ... 1.         1.         1.        ]
 [0.3259853  1.         0.52       ... 1.         0.         1.        ]
 [0.60855043 0.         0.04       ... 0.         0.         1.        ]
 ...
 [0.07214429 1.         1.         ... 1.         0.         1.        ]
 [0.80293921 1.         0.4        ... 1.         1.         1.        ]
 [0.56646627 0.         0.6        ... 1.         0.         0.        ]]


In [155]:
print(x_test)

[[0.8750835  1.         0.8        ... 1.         1.         1.        ]
 [0.05678023 0.         0.         ... 1.         1.         1.        ]
 [0.79358717 1.         0.         ... 1.         0.         0.        ]
 ...
 [0.08149633 1.         0.12       ... 1.         0.         0.        ]
 [0.36138945 0.         0.88       ... 1.         1.         1.        ]
 [0.7748831  1.         0.36       ... 1.         1.         1.        ]]


In [156]:
print(y_train)

994     0
1104    1
1536    1
1130    3
1049    1
       ..
1872    1
1182    0
350     1
372     3
447     2
Name: price_range, Length: 1400, dtype: int64


In [157]:
print(y_test)

1336    2
1112    3
1484    2
164     2
1845    3
       ..
1887    2
834     3
1831    1
401     3
504     0
Name: price_range, Length: 600, dtype: int64


In [160]:
import pandas as pd


In [158]:
h=pd.read_csv("/heart.csv")

In [161]:
print(h)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [162]:
yh=h['target']
xh=h.drop("target",axis=1)
print(xh)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [163]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xhtrain_norm=scaler.fit_transform(xh)

In [164]:
print(xhtrain_norm)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [165]:
from sklearn.model_selection import train_test_split
xh_train,xh_test,yh_train,yh_test=train_test_split(xhtrain_norm,yh,test_size=0.3)

In [166]:
print(xh_train)

[[0.47916667 1.         0.33333333 ... 1.         0.         0.66666667]
 [0.60416667 1.         0.         ... 1.         0.25       1.        ]
 [0.70833333 1.         0.         ... 0.5        0.25       1.        ]
 ...
 [0.27083333 1.         0.66666667 ... 1.         0.         0.66666667]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.54166667 0.         0.33333333 ... 1.         0.         0.66666667]]


In [167]:
print(xh_test)

[[0.83333333 0.         1.         ... 1.         0.5        0.66666667]
 [0.8125     0.         0.66666667 ... 0.5        0.         0.66666667]
 [0.27083333 1.         0.         ... 0.5        0.         0.33333333]
 ...
 [0.60416667 1.         0.66666667 ... 0.5        0.         1.        ]
 [0.33333333 1.         0.         ... 0.5        0.75       1.        ]
 [0.58333333 1.         0.         ... 0.5        0.         0.33333333]]


In [168]:
print(yh_train)

78     1
273    0
168    0
218    0
172    0
      ..
64     1
1      1
149    1
243    0
161    1
Name: target, Length: 212, dtype: int64


In [169]:
print(yh_test)

19     1
105    1
280    0
208    0
216    0
      ..
16     1
233    0
79     1
255    0
138    1
Name: target, Length: 91, dtype: int64


In [174]:
import numpy as np
x1=xh_train[:,0]
x2=xh_train[:,1]
x3=xh_train[:,2]
x4=xh_train[:,3]
x5=xh_train[:,4]
x6=xh_train[:,5]
x7=xh_train[:,6]
x8=xh_train[:,7]
x9=xh_train[:,8]
x10=xh_train[:,9]
x11=xh_train[:,10]
x12=xh_train[:,11]
x13=xh_train[:,12]
y_p=[]
def perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(x1)):
    z=x1[i]*w1+x2[i]*w2+x3[i]*w3+x4[i]*w4+x5[i]*w5+x6[i]*w6+x7[i]*w7+x8[i]*w8+x9[i]*w9+x10[i]*w10+x11[i]*w11+x12[i]*w12+x13[i]*w13+b
    s=1/1+np.exp(-z)
    if(s>=0.5):
     y_p.append(1)
    else:
      y_p.append(0)
perceptron(1,1,1,1,1,1,1,1,1,1,1,1,1,1)


In [175]:
print(perceptron)

<function perceptron at 0x7d9747da9000>


In [176]:
print(y_p)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [177]:
print(len(y_p))

212


In [178]:
l=[]
import numpy as np
np.array(yh_train)==np.array(y_p)
z=np.array(yh_train)
a=sum(z)
b=len(y_p)
print(a/b)

0.5471698113207547
